# Generated by Django 5.2.15 on 2026-06-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srt_id', models.CharField(max_length=100)),
                ('srt_pw', models.CharField(max_length=200)),
                ('dep', models.CharField(max_length=20)),
                ('arr', models.CharField(max_length=20)),
                ('date', models.CharField(help_text='yyyyMMdd', max_length=8)),
                ('time', models.CharField(default='000000', help_text='hhmmss', max_length=6)),
                ('train_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(default='GENERAL_FIRST', max_length=20)),
                ('train_label', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('PENDING', '대기/재시도중'), ('RESERVED', '예약완료'), ('FAILED', '실패'), ('CANCELLED', '취소됨')], default='PENDING', max_length=12)),
                ('attempts', models.IntegerField(default=0)),
                ('last_message', models.TextField(blank=True, default='')),
                ('reservation_number', models.CharField(blank=True, default='', max_length=40)),
                ('result', models.JSONField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
