# Generated by Django 5.1.15 on 2026-06-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationjob',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기/재시도중'), ('PAUSED', '일시중지'), ('RESERVED', '예약완료'), ('FAILED', '실패'), ('CANCELLED', '취소됨')], default='PENDING', max_length=12),
        ),
    ]
