# Generated by Django 5.1.15 on 2026-06-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservationjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationjob',
            name='retry_interval_ms',
            field=models.IntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='reservationjob',
            name='status',
            field=models.CharField(choices=[('QUEUED', '대기중(미시작)'), ('PENDING', '재시도중'), ('PAUSED', '일시중지'), ('RESERVED', '예약완료'), ('FAILED', '실패'), ('CANCELLED', '취소됨')], default='QUEUED', max_length=12),
        ),
    ]
