# Generated by Django 5.1.15 on 2026-06-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_backfill_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationjob',
            name='slack_user_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
