# Generated by Django 5.1.15 on 2026-06-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_reservationjob_slack_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slack_user_id', models.CharField(blank=True, default='', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
