# Generated by Django 5.1.15 on 2026-06-09 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_userpref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationjob',
            name='slack_user_id',
        ),
    ]
