# Generated by Django 5.1.15 on 2026-06-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_remove_reservationjob_slack_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationjob',
            name='dep_time',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='reservationjob',
            name='time',
            field=models.CharField(default='000000', help_text='검색 시작 시각 hhmmss', max_length=6),
        ),
    ]
