# Generated by Django 5.1.15 on 2026-06-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_reservationjob_dep_time_alter_reservationjob_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='srt_pw',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
